"""email_nullable

Revision ID: be938afe4add
Revises: aa3241be1fd2
Create Date: 2026-06-17 23:43:45.435188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'be938afe4add'
down_revision: Union[str, None] = 'aa3241be1fd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.execute("UPDATE users SET email = NULL WHERE email = ''")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
